<?php

return [
    'unknown_entity' => [
        'canonical_name' => 'unknown-encrypted',
        'display_name' => 'Unknown Encrypted',
        'entity_type' => 'unknown',
        'category_name' => 'Unknown Encrypted',
        'metadata' => [
            'resolution' => 'unknown',
            'confidence_label' => 'low',
        ],
    ],
    'groups' => [
        'A' => ['Home Router', 'VLAN20 - Camaymayan', 'VLAN30 - Rutor'],
        'B' => ['VLAN40 - Peleyo', 'VLAN50 - Yamba', 'VLAN60 - Piso WiFi', 'VLAN70 - Olario'],
    ],
    'excluded_queues' => [
        'GROUP_A_TOTAL',
    ],
    'sources' => [
        'ntopng' => [
            'base_url' => env('NTOPNG_BASE_URL'),
            'token' => env('NTOPNG_TOKEN'),
        ],
        'zeek' => [
            'base_path' => env('ZEEK_BASE_PATH'),
        ],
        'flow' => [
            'endpoint' => env('FLOW_ANALYTICS_ENDPOINT'),
        ],
    ],
    'mappings' => [
        [
            'canonical_name' => 'youtube',
            'display_name' => 'YouTube',
            'entity_type' => 'website',
            'category_name' => 'Streaming',
            'vendor_name' => 'Google',
            'domain' => 'youtube.com',
            'aliases' => [
                ['name' => 'youtube.com', 'type' => 'domain'],
                ['name' => 'googlevideo.com', 'type' => 'domain'],
                ['name' => 'ytimg.com', 'type' => 'domain'],
            ],
            'patterns' => ['youtube.com', 'googlevideo.com', 'ytimg.com'],
            'confidence' => 0.97,
            'metadata' => ['resolution' => 'service_family', 'confidence_label' => 'high'],
        ],
        [
            'canonical_name' => 'facebook',
            'display_name' => 'Facebook',
            'entity_type' => 'website',
            'category_name' => 'Social Media',
            'vendor_name' => 'Meta',
            'domain' => 'facebook.com',
            'aliases' => [
                ['name' => 'facebook.com', 'type' => 'domain'],
                ['name' => 'fbcdn.net', 'type' => 'domain'],
            ],
            'patterns' => ['facebook.com', 'fbcdn.net'],
            'confidence' => 0.95,
            'metadata' => ['resolution' => 'exact_or_suffix', 'confidence_label' => 'high'],
        ],
        [
            'canonical_name' => 'instagram',
            'display_name' => 'Instagram',
            'entity_type' => 'app',
            'category_name' => 'Social Media',
            'vendor_name' => 'Meta',
            'domain' => 'instagram.com',
            'aliases' => [
                ['name' => 'instagram.com', 'type' => 'domain'],
                ['name' => 'cdninstagram.com', 'type' => 'domain'],
            ],
            'patterns' => ['instagram.com', 'cdninstagram.com'],
            'confidence' => 0.95,
            'metadata' => ['resolution' => 'service_family', 'confidence_label' => 'high'],
        ],
        [
            'canonical_name' => 'tiktok',
            'display_name' => 'TikTok',
            'entity_type' => 'app',
            'category_name' => 'Social Media',
            'vendor_name' => 'ByteDance',
            'domain' => 'tiktok.com',
            'aliases' => [
                ['name' => 'tiktok.com', 'type' => 'domain'],
                ['name' => 'tiktokcdn.com', 'type' => 'domain'],
            ],
            'patterns' => ['tiktok.com', 'tiktokcdn.com'],
            'confidence' => 0.94,
            'metadata' => ['resolution' => 'service_family', 'confidence_label' => 'high'],
        ],
        [
            'canonical_name' => 'netflix',
            'display_name' => 'Netflix',
            'entity_type' => 'app',
            'category_name' => 'Streaming',
            'vendor_name' => 'Netflix',
            'domain' => 'netflix.com',
            'aliases' => [
                ['name' => 'netflix.com', 'type' => 'domain'],
                ['name' => 'nflxvideo.net', 'type' => 'domain'],
            ],
            'patterns' => ['netflix.com', 'nflxvideo.net'],
            'confidence' => 0.97,
            'metadata' => ['resolution' => 'service_family', 'confidence_label' => 'high'],
        ],
        [
            'canonical_name' => 'steam',
            'display_name' => 'Steam / Valve services',
            'entity_type' => 'game_service',
            'category_name' => 'Gaming',
            'vendor_name' => 'Valve',
            'domain' => 'steampowered.com',
            'aliases' => [
                ['name' => 'steam', 'type' => 'app_label'],
                ['name' => 'steamcontent.com', 'type' => 'domain'],
                ['name' => 'steampowered.com', 'type' => 'domain'],
            ],
            'patterns' => ['steam', 'steamcontent.com', 'steampowered.com'],
            'confidence' => 0.93,
            'metadata' => ['resolution' => 'service_family', 'confidence_label' => 'medium'],
        ],
        [
            'canonical_name' => 'riot',
            'display_name' => 'Riot services',
            'entity_type' => 'game_service',
            'category_name' => 'Gaming',
            'vendor_name' => 'Riot Games',
            'domain' => 'riotgames.com',
            'aliases' => [
                ['name' => 'riotgames', 'type' => 'app_label'],
                ['name' => 'riotgames.com', 'type' => 'domain'],
                ['name' => 'valorant', 'type' => 'app_label'],
            ],
            'patterns' => ['riotgames', 'riotgames.com', 'valorant'],
            'confidence' => 0.9,
            'metadata' => ['resolution' => 'possible_family', 'confidence_label' => 'medium'],
        ],
        [
            'canonical_name' => 'epic-games',
            'display_name' => 'Epic Games',
            'entity_type' => 'game_service',
            'category_name' => 'Gaming',
            'vendor_name' => 'Epic Games',
            'domain' => 'epicgames.com',
            'aliases' => [
                ['name' => 'epicgames.com', 'type' => 'domain'],
                ['name' => 'epicgames', 'type' => 'app_label'],
            ],
            'patterns' => ['epicgames.com', 'epicgames'],
            'confidence' => 0.92,
            'metadata' => ['resolution' => 'service_family', 'confidence_label' => 'medium'],
        ],
        [
            'canonical_name' => 'discord',
            'display_name' => 'Possible Discord traffic',
            'entity_type' => 'app',
            'category_name' => 'Communication',
            'vendor_name' => 'Discord',
            'domain' => 'discord.com',
            'aliases' => [
                ['name' => 'discord.com', 'type' => 'domain'],
                ['name' => 'discord.gg', 'type' => 'domain'],
                ['name' => 'discord', 'type' => 'app_label'],
            ],
            'patterns' => ['discord.com', 'discord.gg', 'discord'],
            'confidence' => 0.82,
            'metadata' => ['resolution' => 'possible_family', 'confidence_label' => 'medium'],
        ],
    ],
    'category_fallbacks' => [
        'video' => 'Streaming',
        'streaming' => 'Streaming',
        'gaming' => 'Gaming',
        'social' => 'Social Media',
        'social_media' => 'Social Media',
        'chat' => 'Communication',
        'communication' => 'Communication',
        'web' => 'Browsing',
        'browsing' => 'Browsing',
        'download' => 'Downloads',
        'downloads' => 'Downloads',
        'encrypted' => 'Unknown Encrypted',
        'unknown' => 'Unknown Encrypted',
    ],
];
